# Generated by Django 3.1.5 on 2021-01-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaptopProduct',
            new_name='Laptop',
        ),
    ]
