# Generated by Django 3.1.5 on 2021-01-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210127_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smarphone',
            new_name='Smartphone',
        ),
    ]
