# Generated by Django 3.1.5 on 2021-01-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210127_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='personalcomputer',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='averageRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Average rate'),
        ),
    ]
