# Generated by Django 3.1.5 on 2021-01-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210128_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Diagonal'),
        ),
    ]
