# Generated by Django 3.1.5 on 2021-02-02 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210202_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_buy',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
