# Generated by Django 3.1.5 on 2021-02-03 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_date_buy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_buy',
            new_name='date_delivery',
        ),
        migrations.AddField(
            model_name='feedback',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.PositiveIntegerField(verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Diagonal'),
        ),
    ]
