# Generated by Django 3.1.5 on 2021-02-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210203_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='personalcomputer',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
    ]
