# Generated by Django 3.1.5 on 2021-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210204_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Diagonal'),
        ),
    ]
