# Generated by Django 3.1.5 on 2021-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
